spring.application.name=Subtrack

spring.datasource.url=jdbc:postgresql://localhost:5433/subtrack
spring.datasource.username=subtrack_user
spring.datasource.password=subtrack_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.liquibase.enabled=true