package com.subtrack.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a grouping under which subscriptions are classified
 * (for example, "Streaming", "Music", or "Productivity").
 *
 * <p>A category is the inverse side of its relationship with
 * {@link Subscription}; each subscription carries the foreign key back to
 * its category.</p>
 */
@Entity
@Table(name = "categories")
public class Category {

    /** Surrogate primary key, generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique, human-readable category name. Must not be blank. */
    @NotBlank(message = "Category name is required")
    @Column(nullable = false, unique = true)
    private String name;

    /** Optional free-text description of the category. */
    @Column(length = 500)
    private String description;

    /**
     * Subscriptions classified under this category.
     *
     * <p>Mapped by the {@code category} field on {@link Subscription}. No
     * cascade is applied: deleting a category does not delete its
     * subscriptions, which keeps reference data independent of user data.</p>
     */
    @OneToMany(mappedBy = "category")
    private List<Subscription> subscriptions = new ArrayList<>();

    /** Default no-args constructor required by JPA. */
    public Category() {
    }

    /**
     * Convenience constructor for the core category fields.
     *
     * @param name        the unique category name
     * @param description an optional description
     */
    public Category(String name, String description) {
        this.name = name;
        this.description = description;
    }

    /**
     * Returns the primary key.
     *
     * @return the category id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the primary key.
     *
     * @param id the category id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the category name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the category name.
     *
     * @param name the name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description.
     *
     * @return the description, possibly {@code null}
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description.
     *
     * @param description the description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the subscriptions classified under this category.
     *
     * @return the list of subscriptions (never {@code null})
     */
    public List<Subscription> getSubscriptions() {
        return subscriptions;
    }

    /**
     * Replaces the subscriptions classified under this category.
     *
     * @param subscriptions the list of subscriptions
     */
    public void setSubscriptions(List<Subscription> subscriptions) {
        this.subscriptions = subscriptions;
    }
}