package com.subtrack.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Represents a single paid subscription tracked by a {@link User}
 * (for example, Spotify, Netflix, or YouTube Premium).
 *
 * <p>Each subscription is owned by exactly one user and classified under
 * exactly one {@link Category}. It holds the foreign keys for both
 * relationships, making it the owning side of each association.</p>
 */
@Entity
@Table(name = "subscriptions")
public class Subscription {

    /** Surrogate primary key, generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Display name of the subscribed service. Must not be blank. */
    @NotBlank(message = "Subscription name is required")
    @Column(nullable = false)
    private String name;

    /** Optional free-text description of the subscription. */
    @Column(length = 500)
    private String description;

    /** Recurring price per billing cycle. Must be a positive amount. */
    @NotNull(message = "Price is required")
    @Positive(message = "Price must be greater than zero")
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal price;

    /** ISO 4217 currency code for the price (for example, "EUR" or "USD"). */
    @NotBlank(message = "Currency is required")
    @Column(nullable = false, length = 3)
    private String currency;

    /** Frequency at which the subscription is billed. */
    @NotNull(message = "Billing cycle is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "billing_cycle", nullable = false)
    private BillingCycle billingCycle;

    /** Date on which the subscription is next due to renew. */
    @NotNull(message = "Next renewal date is required")
    @Column(name = "next_renewal_date", nullable = false)
    private LocalDate nextRenewalDate;

    /** Whether the subscription is currently active. */
    @Column(nullable = false)
    private boolean active = true;

    /**
     * Owning user of this subscription.
     *
     * <p>Lazily fetched to avoid loading the user (and, transitively, all of
     * their subscriptions) on every query.</p>
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Category under which this subscription is classified.
     *
     * <p>Lazily fetched. Required so that every subscription is classifiable.</p>
     */
    @NotNull(message = "Category is required")
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    /** Default no-args constructor required by JPA. */
    public Subscription() {
    }

    /**
     * Convenience constructor for the core subscription fields.
     *
     * @param name            the service name
     * @param description     an optional description
     * @param price           the recurring price
     * @param currency        the ISO 4217 currency code
     * @param billingCycle    the billing frequency
     * @param nextRenewalDate the next renewal date
     * @param active          whether the subscription is active
     */
    public Subscription(String name, String description, BigDecimal price, String currency,
                        BillingCycle billingCycle, LocalDate nextRenewalDate, boolean active) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.currency = currency;
        this.billingCycle = billingCycle;
        this.nextRenewalDate = nextRenewalDate;
        this.active = active;
    }

    /**
     * Returns the primary key.
     *
     * @return the subscription id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the primary key.
     *
     * @param id the subscription id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the service name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the service name.
     *
     * @param name the name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description.
     *
     * @return the description, possibly {@code null}
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description.
     *
     * @param description the description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the recurring price.
     *
     * @return the price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the recurring price.
     *
     * @param price the price
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Returns the ISO 4217 currency code.
     *
     * @return the currency code
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the ISO 4217 currency code.
     *
     * @param currency the currency code
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Returns the billing frequency.
     *
     * @return the billing cycle
     */
    public BillingCycle getBillingCycle() {
        return billingCycle;
    }

    /**
     * Sets the billing frequency.
     *
     * @param billingCycle the billing cycle
     */
    public void setBillingCycle(BillingCycle billingCycle) {
        this.billingCycle = billingCycle;
    }

    /**
     * Returns the next renewal date.
     *
     * @return the next renewal date
     */
    public LocalDate getNextRenewalDate() {
        return nextRenewalDate;
    }

    /**
     * Sets the next renewal date.
     *
     * @param nextRenewalDate the next renewal date
     */
    public void setNextRenewalDate(LocalDate nextRenewalDate) {
        this.nextRenewalDate = nextRenewalDate;
    }

    /**
     * Returns whether the subscription is active.
     *
     * @return {@code true} if active, otherwise {@code false}
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets whether the subscription is active.
     *
     * @param active the active flag
     */
    public void setActive(boolean active) {
        this.active = active;
    }

    /**
     * Returns the owning user.
     *
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the owning user.
     *
     * @param user the user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Returns the category.
     *
     * @return the category
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the category.
     *
     * @param category the category
     */
    public void setCategory(Category category) {
        this.category = category;
    }
}