package com.subtrack.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents an application account that owns subscriptions.
 *
 * <p>A user authenticates with a unique {@code username} and {@code email},
 * and may track any number of {@link Subscription} records. The relationship
 * to subscriptions is the owning side's inverse: each subscription holds the
 * foreign key back to its user.</p>
 */
@Entity
@Table(name = "users")
public class User {

    /** Surrogate primary key, generated by the database identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique login name. Must not be blank. */
    @NotBlank(message = "Username is required")
    @Column(nullable = false, unique = true)
    private String username;

    /** Unique, syntactically valid email address. Must not be blank. */
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be a valid address")
    @Column(nullable = false, unique = true)
    private String email;

    /** Hashed account password. Must not be blank. Never exposed via DTOs. */
    @NotBlank(message = "Password is required")
    @Column(nullable = false)
    private String password;

    /**
     * Subscriptions owned by this user.
     *
     * <p>Mapped by the {@code user} field on {@link Subscription}. Cascading
     * persists and removes child subscriptions together with their owner, and
     * orphan removal deletes a subscription once it is detached from this list.</p>
     */
    @OneToMany(
            mappedBy = "user",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<Subscription> subscriptions = new ArrayList<>();

    /** Default no-args constructor required by JPA. */
    public User() {
    }

    /**
     * Convenience constructor for the core account fields.
     *
     * @param username the unique login name
     * @param email    the unique email address
     * @param password the hashed password
     */
    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }

    /**
     * Adds a subscription to this user and synchronises the back-reference.
     *
     * @param subscription the subscription to associate with this user
     */
    public void addSubscription(Subscription subscription) {
        subscriptions.add(subscription);
        subscription.setUser(this);
    }

    /**
     * Removes a subscription from this user and clears the back-reference.
     *
     * @param subscription the subscription to disassociate from this user
     */
    public void removeSubscription(Subscription subscription) {
        subscriptions.remove(subscription);
        subscription.setUser(null);
    }

    /**
     * Returns the primary key.
     *
     * @return the user id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the primary key.
     *
     * @param id the user id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the unique username.
     *
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the unique username.
     *
     * @param username the username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns the email address.
     *
     * @return the email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address.
     *
     * @param email the email address
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the hashed password.
     *
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the hashed password.
     *
     * @param password the password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the subscriptions owned by this user.
     *
     * @return the list of subscriptions (never {@code null})
     */
    public List<Subscription> getSubscriptions() {
        return subscriptions;
    }

    /**
     * Replaces the subscriptions owned by this user.
     *
     * @param subscriptions the list of subscriptions
     */
    public void setSubscriptions(List<Subscription> subscriptions) {
        this.subscriptions = subscriptions;
    }
}